// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentGateway.Infrastructure.Persistence;

#nullable disable

namespace PaymentGateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentGatewayDbContext))]
    partial class PaymentGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentGateway.Infrastructure.Persistence.Entities.DbOperation", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("LastEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("NextDispatchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProviderPaymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OperationId")
                        .HasName("pk_operations");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_operations_providerpaymentid");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("PaymentGateway.Infrastructure.Persistence.Entities.DbOperationEvent", b =>
                {
                    b.Property<string>("OperationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId", "EventId")
                        .HasName("pk_operation_events");

                    b.ToTable("operation_events", (string)null);
                });

            modelBuilder.Entity("PaymentGateway.Infrastructure.Persistence.Entities.DbReceipt", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ProviderPaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReceiptId")
                        .HasName("pk_receipts");

                    b.HasIndex("OperationId", "ProviderPaymentId", "Result")
                        .IsUnique()
                        .HasDatabaseName("ux_receipts_operationid_providerpaymentid_result");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("PaymentGateway.Infrastructure.Persistence.Entities.DbOperationEvent", b =>
                {
                    b.HasOne("PaymentGateway.Infrastructure.Persistence.Entities.DbOperation", "Operation")
                        .WithMany("OperationEvents")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_events_operations_operationid");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("PaymentGateway.Infrastructure.Persistence.Entities.DbReceipt", b =>
                {
                    b.HasOne("PaymentGateway.Infrastructure.Persistence.Entities.DbOperation", "Operation")
                        .WithMany("Receipts")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_operations_operationid");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("PaymentGateway.Infrastructure.Persistence.Entities.DbOperation", b =>
                {
                    b.Navigation("OperationEvents");

                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
